### ISSUE TITLE
VectrasVM crash in Android 13

### ISSUE THREAD

**Issue by RICKHDEX** [epicstudios856/Vectras-VM-Android#40]
When I opened the app for the first time it crashed and I couldn't use it

Log:
Time Of Crash :    2024_04_14-18_43_23
Device :    Xiaomi, 220333QL
Android Version :    13 (33)
App Version :    v2.8-debug-build-4 (14)
Kernel :    /proc/version: open failed: EACCES (Permission denied)
Support Abis :    [arm64-v8a, armeabi-v7a, armeabi]
Fingerprint :    Redmi/wind_global/wind:13/TKQ1.221114.001/V14.0.6.0.TGEMIXM:user/release-keys

android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:10348)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:2136)
	at android.view.View.requestLayout(View.java:26610)
	at android.view.View.requestLayout(View.java:26610)
	at android.view.View.requestLayout(View.java:26610)
	at android.view.View.requestLayout(View.java:26610)
	at android.view.View.requestLayout(View.java:26610)
	at android.view.View.requestLayout(View.java:26610)
	at android.view.View.requestLayout(View.java:26610)
	at android.view.View.requestLayout(View.java:26610)
	at android.view.View.requestLayout(View.java:26610)
	at android.view.View.requestLayout(View.java:26610)
	at android.view.View.setFlags(View.java:16952)
	at android.view.View.setVisibility(View.java:12369)
	at com.vectras.vm.SetupQemuActivity.lambda$executeShellCommand$4$com-vectras-vm-SetupQemuActivity(SetupQemuActivity.java:183)
	at com.vectras.vm.SetupQemuActivity$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by Ankushpala** [comment]
Hi sir I am ankush

**Comment by Ankushpala** [comment]
![Uploading inbound3765804593682822045.jpg…]()

**Comment by Ankushpala** [comment]
Hi sir my name is **ankush_******

**Comment by epicstudios856** [comment]
issue fixed here!
https://github.com/epicstudios856/Vectras-VM-Android/releases/tag/v2.8.5
