### ISSUE TITLE
Samsung Crash

### ISSUE THREAD

**Issue by Loading617** [epicstudios856/Vectras-VM-Android#47]
Time Of Crash :    2024_04_20-12_36_32
Device :    samsung, SM-A156U
Android Version :    14 (34)
App Version :    v2.8-debug-build-5 (15)
Kernel :    /proc/version: open failed: EACCES (Permission denied)
Support Abis :    [arm64-v8a, armeabi-v7a, armeabi]
Fingerprint :    samsung/a15xsq/a15x:14/UP1A.231005.007/A156USQS1AXA3:user/release-keys

java.lang.RuntimeException: java.io.IOException: write failed: ENOSPC (No space left on device)
	at com.vectras.vm.RomsManagerActivity$6.run(RomsManagerActivity.java:501)
Caused by: java.io.IOException: write failed: ENOSPC (No space left on device)
	at libcore.io.IoBridge.write(IoBridge.java:651)
	at java.io.FileOutputStream.write(FileOutputStream.java:406)
	at com.vectras.vm.RomsManagerActivity$6.run(RomsManagerActivity.java:489)
Caused by: android.system.ErrnoException: write failed: ENOSPC (No space left on device)
	at libcore.io.Linux.writeBytes(Native Method)
	at libcore.io.Linux.write(Linux.java:296)
	at libcore.io.ForwardingOs.write(ForwardingOs.java:943)
	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:448)
	at libcore.io.ForwardingOs.write(ForwardingOs.java:943)
	at libcore.io.IoBridge.write(IoBridge.java:646)
	... 2 more

**Comment by epicstudios856** [comment]
ENOSPC (No space left on device)
